---
title: STAT 801A (Fall 2026)
subtitle: Statistical Methods In Research -- Non Calculus
format:
  html: default
---

# Instructor

Name: Tyler Wiederich, Ph.D. \
Office: Hardin Hall 343A \
Office hours: W 1-3.\
E-mail: [twiederich2@unl.edu](mailto:twiederich2@unl.edu)


All office hours are guaranteed for the first 30 minutes. If no students are present after 30 minutes, office hours are ended.

# Course Description

Probability calculus; random variables, their probability distributions and expected values; t, F and chi-square sampling distributions; estimation; testing of hypothesis; and regression analysis with applications.

# Assessments

This course consists of projects/quizzes, a midterm, and a final. 

**Projects/Quizzes**: Projects and quizzes will be assigned periodically throughout the semester. You will have at least one week to complete the assessment.

**Midterm**: There will be one midterm approximately halfway through the semester. Details will be provided in class.

**Final**: To be announced in class.

These assessments are weighted as follows:

| | Projects/quizzes\* | Midterm | Final | 
| :---: | :---: | :---: | :---: |
| % of grade | 20% | 30% | 50% |

\*All projects need to be turned electronically via PDF documents. A project completed in an unreadable or unprofessional manner will be returned for a zero grade. Quizzes will be assigned on Canvas. No late projects or quizzes are accepted.

If projects allow for group work, all group members are expected to participate equally and have a complete understanding of all components for it. I will lower a student's project grade if he/she/they do not abide by this group work policy.

# Grades

Your overall course grade percentage guarantees the following grade for the course.

| Letter Grade | + | | - |
| :-----: | :---: | :---: | :---: | :---: |
| A | | 93 | 90 |
| B | 87 |  83 | 80 |
| C | 77 | 73 | 70 |
| D | 67 | 63 | 60 | 
| F | | <60 | |


# Continuity of Instruction Policy

In the event that the university is closed during our regular class hours, please check the Canvas announcements for alternative class arrangements.

# AI Disclaimer

The recent popularity of large language models and other artificial intelligence tools introduces a unique challenge in the academic community. As an instructor, my goal is to promote critical thinking for the topics taught in this course. Unless otherwise stated, **the use of AI tools is not permitted**. If you are suspected of using AI, I reserve the right to give a zero grade.


\newpage

# Tentative Topics

- Probability
- 


\*The final will be held in-person on Monday, Dec. 14 from 10:00 to noon. 

# UNL Course Policies and Resources

Students are responsible for knowing the university policies and resources found on this page: <https://go.unl.edu/coursepolicies>

- University-wide Attendance Policy
- Academic Honesty Policy
- Services for Students with Disabilities
- Mental Health and Well-Being Resources
- Final Exam Schedule
- Fifteenth Week Policy
- Emergency Procedures
- Diversity & Inclusiveness
- Title IX Policy
- Other Relevant University-Wide Policies