---
date: today
date-format: "[Fall 2026]"
format:
  pdf: 
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \lhead{STAT 380}
        \chead{Handout 2}
        \rhead{Fall 2026}
        \rfoot{\thepage}
        \setlength{\headheight}{14pt}
    fig-align: center
---

## Terminology {#slide-3}

**Experiment**: an activity or process with an uncertain outcome. This can be repeated any number of times.

**Sample Outcome** ($s, \omega$) is any possible outcome.

**Sample Space** ($S, \Omega$) is the collection of all possible outcomes of the experiment.

**Event** ($A\subseteq S$) is any designated subset of $S$.

## Experiment {#slide-4}

All statistical experiments have three things in common:

- The experiment can have more than one possible outcome.
- Each possible outcome can be specified in advance.
- The outcome of the experiment depends on chance.

For example, consider flipping a coin. What are the possible outcomes? If the flip is fair, would you know what side of the coin is shown?

\
\
\
\
\
\
\

## Sample space {#slide-6}

The sample space is the collection of all possible outcomes of the experiment. What are the outcomes for the following scenarios?

1. Flipping a coin three times.
\
\
\
\
\
2. A deck of cards only containing clubs.
\
\
\
\
\
3. Completion time of a mile run.
\
\
\
\
\

## Event

An event is a subset of the sample space. It is usually denoted by a capital letter. If a coin is tossed and you observe the top face, which of the following are a valid event?

- $A=\{H\}$
- $A=\{T\}$
- $A=\{3\}$
- $A=\{TT\}$

A **Null Set** is an event with no elements and is denoted by $\phi$, or sometimes by $\{\}$

## Set Operations

Consider two events $A$ and $B$. 

Union (“or”)

- Elements in one or both sets
- $\omega\in A\cup B$ provided $\omega\in A$ or $\omega\in B$

Intersection (“and”)

- Elements in both sets
- $\omega\in A\cap B$ provided $\omega\in A$ and $\omega\in B$

Complement (“not”)

- Elements not in the set
- $\omega\in A^C$ or $A^\prime$ provided $\omega\notin A$

\newpage

Consider only the clubs from a standard 52-card deck (A,2,3,...,10,J,Q,K) and the following events.

- $A=$ numeric and even cards (2,4,6,8,10)
- $B=$ face cards (J,Q,K)

What are the unions, intersections, and complements of $A$ and $B$?

\newpage

## Set Properties

The following are set properties and 

- $A\cap\phi$
\
- $A\cup\phi$
\
- $A\cap A^\prime$
\
- $A\cup A^\prime$
\
- $S^\prime$
\
- $(A^\prime)^\prime$
\
- $\phi'$
\

Events $A$ and $B$ are mutually exclusive (disjoint) if an only if $A\cap B=\phi$.

DeMorgan's Laws

- $(A\cap B)^\prime$
\
- $(A\cup B)^\prime$

## Counting {#slide-21}

In many experiments, it is not feasible to list all possible elements in a sample space or an event. Yet to compute probabilities, we need to know how many elements there are. The rules in this section will help us count the number of elements in a sample space.

Toss a coin twice then the first toss can result in \_\_\_\_ different ways and the second toss can result in \_\_\_\_ different ways. Two tosses of a coin can result in \_\_\_\_\_\_\_\_\_\_\_different ways.

The fundamental principle we look at is called the multiplication rule. If an operation can be performed in $n_1$ ways, and if for each of these ways a second operation can be performed in $n_2$ ways, then the two operations can be performed together in $n_1\times n_2$ ways. If there are $k$ such operations, the total number of operations can be performed together in $n_1\times n_2\times\dots n_k$ ways. An assumption of the multiplication rule is that each operation does not have an effect on the outcome of the other operations.

How many outcomes are in the sample space of the following operations?

- Rolling two standard six-sided dice.

\
\
\

- Outfits between 5 shirts, 3 pants, and 2 pairs of shoes.

\
\
\

## Permutations

Permutation is an arrangement of all or part of a set of objects. For example, the letters a, b, and c can be arranged as 

\
\
\
\
\

The number of permutations of $n$ different objects is $n$ factorial, denoted by $n!$, where

$$
n!=n\times(n-1)\times(n-2)\times\dots\times 3\times 2 \times 1
$$

In many cases, some of the objects in the set are identical. For example, the collection $\{a,a,b\}$ could be arranged as $\{aab,aba,baa\}$. To count the number of unique arrangements with identical objects, we divide the total number of arrangements by the factorial of each kind of object.

If there are $r$ kinds of objects, the number of permutations is given by 

$$
\frac{n!}{n_1!n_2!\dots n_r!}
$$

Example: suppose that you are arranging the letters of MINNESOTA. How many distinct ways can the letters be arranged? 

\
\
\
\
\
\
\
\
\
\

Permutations do not need to select every object. For example, in a club of 30 students and three officer positions (president, vice president, and treasurer), the ordering of non-officer students is not considered. For $r$ objects from a set of $n$ objects, the number of permutations is

$$
\frac{n!}{(n-r)!}
$$

Using the club example, there are $\frac{30!}{(30-3)!}$ permutations of club officers.

## Combinations

When the ordering of objects is not important, the selections of some objects from the set of objects are called combinations. This is the counting of unordered sets and subsets.

The number of combinations of $r$ objects from a set of $n$ objects is:

$$
{n\choose r}=\frac{n!}{(n-r)!r!}
$$

Example: suppose that your grandma has an envelope of each common denomination of dollar bill (\$1, \$5, \$10, \$20, \$50, \$100). She let's you select three of the dollar bills at random. How many possible combinations of bills can you draw from the envelope?

\newpage

## Counting Summary

To recap, we covered the following scenarios:

- Multiplication (different independent operations)

\
\
\

- Ordered, without replacement

\
\
\

- Ordered, with replacement


\
\
\

- Unordered with unique objects, without replacement

\
\
\

## Probability

Probability is the likelihood of an event occurring, usually denoted for event $A$ as $P(A)$. This measures the percent of times that $A$ occurs out of an infinite number of repeated experiments.

For example, let $S=\{\text{Rain}, \text{No Rain}\}$, where $A=\text{Rain}$. If there is a 20% chance of rain, then $P(A)=0.2$ and $P(A^\prime)=0.8$

Let $A\subset S$ be a feasible event. Then

$$
P(A)=\sum_{\omega\in A}p(\omega)
$$

That is, the mass of $A$ is the sum of the masses of the outcomes in $A$. If all outcomes in $S$ are equally likely, this is simply:

\
\
\
\
\

Example: consider a production line producing a certain type of fuse. Select two fuses for close examination and classify each as non-defective (N) or defective (D). 

- What is the sample space?
- If $A$ is the event with no defective fuses, $B$ is the event that at least one fuse is defective, and $C$ is the event where no more than 1 fuse is defective, find $P(A)$, $P(B)$, and $P(C)$



\
\
\
\
\
\
\

There are three essential properties of probabilities:

- $P(A)\geq 0$
- $P(A)\leq 1$
- $P(S)=1$


In addition, we also have the following properties:

- Complements: $P(A^C)=1-P(A)$
- Empty Set: $P(\phi)=0$
- Subsets: $A\subseteq B \rightarrow P(A)\leq P(B)$
- Unions: $P(A\cup B)=P(A)+P(B)-P(A\cap B)$

In class exercises: 

Let two standard six-sided dice be tossed, and $A=\{\text{Sum is even}\}$, $B=\{\text{Sum is less than 5}\}$, and $C=\{\text{Sum is odd}\}$. Find the following probabilities:

- $P(A)$

\
\
\

- $P(B)$

\
\
\

- $P(A\cup B)$

\
\
\

- $P(A\cap B)$

\
\
\

- $P(A^\prime\cup B)$

\
\
\

- $P(A\cup C)$

\
\
\

- $P(A\cap C)$

\
\
\

## Conditional Probability and Independence

In conditional probabilities, some information about the outcome is known. Probability is calculated conditional on that knowledge. Let $P(A|B)$ denote the probability of an event $A$ given that we know $B$. Then:

$$
P(A|B)=\frac{P(A\cap B)}{P(B)}
$$

Example: suppose that in a population, 60% of people have brown hair, 40% have brown eyes, and 30% have both. If you randomly sample a brown-haired person, what is the probability that this person will have brown eyes?

\
\
\
\
\
\
\

Two events, $A$ and $B$, are said to be **independent** if they satisfy $P(A|B)=P(A)$. In our class, showing independence must be through showing that this property holds. 

Example: let a standard six-sided die be tossed, and $A$ be an observed odd number, $B$ be an observed even number, and $C$ be an observed 1 or 2.

- Are $A$ and $B$ independent?

\
\
\
\
\
\
\

- Are $A$ and $C$ independent?
