---
title: "Project 1"
date: "9/11/26"
date-format: "MMMM D, YYYY [by 5 p.m.]"
published-title: "Due date"
format: 
  html: default
  pdf: default
---

Complete each of the following problems. To submit this project, you must type your solutions using your preferred software (e.g., Word, LaTeX, or Typst) and submit your work as a PDF. For each problem, you must show your work in order to receive credit. No credit will be received if you do not show your work. You may include scans of handwritten work, but the final solution must be typed.

1. How many different permutations are there of the letters A, B, C, D, E, F for which

    a. A and B are next to each other
    b. E is not last in line 

2. A committee of 6 people is to be chosen from a group consisting of 7 men and 8 women. How many different committees are possible? 

3. Following question 2, if at least 3 women and at least 2 men are required, how many different committees are possible? 

4. Suppose that two cards are drawn without replacement from a standard 52-card deck (no jokers). Let $A$ be the event that at least one spade is drawn, and let $B$ be the event that at least one queen is drawn. Are $A$ and $B$ independent events? Justify your answer using the mathematical definition of independence.