---
title: "Project 2"
date: "9/28/26"
date-format: "MMMM D, YYYY [by 11:59 p.m.]"
published-title: "Due date"
format: 
  html: default
  pdf: default
---

Complete each of the following problems. To submit this project, you must type your solutions using your preferred software (e.g., Word, LaTeX, or Typst) and submit your work as a PDF. For each problem, you must show your work in order to receive credit. No credit will be received if you do not show your work. You may include scans of handwritten work, but the final solution must be typed.

---

Computer chips are required to be kept at cool temperatures in order to operate efficiently. Let $Y$ denote the temperature in °C, above a baseline temperature, of a randomly selected computer chip. The machine operates in such a way that a different cooling process begins once the chip temperature exceeds 1 degree above the baseline. The pdf of the chip temperature between 0 and 1 °C above the baseline measurement is provided below: 

$$
f_Y(y)=y+c_1;\quad 0<y<1
$$



1. Find the value of $c_1$ that produces a valid pdf for the temperature of the chip. 
2. Compute $E[Y]$.
3. Compute $V[Y]$.
4. Your colleague decides to use Fahrenheit in their report, which is computed as $°F = \frac{9}{5}°C$. Help them with their calculations by computing the expectation and variance of $T$ in °F. 

A performance metric is determined by the chip temperature and fan rotation speed (for cooling) due to their combined power draw. Let $X$ be the random variable of the fan rotation speed and bounded by 0 and 2 units above its baseline. The joint pdf of $X$ and $Y$ is provided below. 

$$
f_{X,Y}(x,y)=\frac{1}{4}(x+2y);\quad 0<y<1,\ 0<x<2
$$
Note: for all distributions, you MUST provide the support as part of your solution.

5. If the temperature of the computer chip is known, determine the distribution of the fan rotation speed (i.e., distribution of $X|Y=y$).
6. Using the conditional distribution of $X|Y=y$, compute the CDF (i.e., $F_{X|Y}(x|y)$).
7. Find $Corr(X,Y)$ and provide a brief statement (1-2 sentences) on what this means.

