---
title: "midterm3"
format: html
---

https://journals.sagepub.com/doi/10.1177/2515245917744314

Thus far, we have discussed set theory and probability distributions. However, we have not talked about how to fit distributions to data, which is an important topic in statistics. For this midterm, you will take the skills you have learned and apply them to estimating distribution parameters. 

Read the following article on Maximum Likelihood Estimation (MLE), which can be accessed through UNL's library. 

> Myung, In Jae. “Tutorial on Maximum Likelihood Estimation.” Journal of Mathematical Psychology, vol. 47, no. 1, Feb. 2003, pp. 90–100, https://doi.org/10.1016/S0022-2496(02)00028-7.

---

**Questions from reading**

1. Describe the purpose of maximum likelihood estimation. How would we use this in our course? (2-4 sentences)

2. What is the difference between the pdf, $f(y|w)$, and the likelihood function, $f(w|y)$? (1-3 sentences)

3. Describe the process of maximum likelihood estimation. What steps do you need to take for the estimation? What is goal? (3-5 sentences)

---

**Connecting MLE's to our course**

4. Suppose you take a sample of size $n$ from a population with a known pdf, and each observation is i.i.d. (independently and identically distributed). The joint pdf for the sample is the product of the pdfs for each $X_i$. That is, for $X_1,X_2,\dots,X_n\sim \text{Some pdf}$, $$f(x=(x_1,x_2,\dots,x_n))=\prod_{i=1}^{n}f(x_i)=f(x_1)\times f(x_2)\times\dots\times f(x_n)$$ Explain why this makes sense using properties of set theory and probability functions discussed in our course. (2-4 sentences)


5. Suppose that your sample from above came from an exponential distribution. Recall that the exponential distribution is defined as follows: $$f(x)=\frac{1}{\beta}e^{-x/\beta};\quad x>0,\ \beta>0$$ Write the log-likelihood function for the observed sample and simplify the expression so that $\sum_{i=1}^n x_i$ is present in your solution.

```{r}
set.seed(380)
y <- rexp(n=10, rate = 0.5)
```

6. The MLE estimator of $\beta$ is $\hat{\beta}=\bar{x}$. 

7. In class, we showed how to derive $E[X]=\beta$ when $X\sim Exp(\beta)$. Derive $E[X^2]$ and find $V(X)$.

8. Using $\hat{\beta}$ and the properties derived in problem (7), what is the expectation and variance of this population?

9. An important assumption is that each element from our sample was independently drawn from the same population. What does this say about $\text{Corr}(X_1, X_2)$?

10. 







